const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches,finePointer=matchMedia('(pointer:fine)').matches,canvas=document.querySelector('#system-field'),ctx=canvas.getContext('2d',{alpha:true}),cursor=document.querySelector('.cursor'),systemItems=[...document.querySelectorAll('.system-item')],projectButtons=[...document.querySelectorAll('.project-index button')];
const projects=[{title:'GP LUBRICANTS',description:'A brand and campaign system for a lubricant business.',type:'BRAND / CAMPAIGN / DIGITAL'},{title:'VIRAL VORTEX GPT',description:'A custom GPT designed to organize prompts and content workflows.',type:'AI / CUSTOM GPT / AUTOMATION'},{title:'VIRALPROMPT.GOD',description:'A prompt and content assistant for creators.',type:'AI TOOLS / PROMPT SYSTEMS / CREATOR WORKFLOWS'}];
let width=0,height=0,dpr=1,pointerX=.5,pointerY=.5,scrollProgress=0,activeSystem=0,activeProject=0;
function resize(){dpr=Math.min(devicePixelRatio,2);width=innerWidth;height=innerHeight;canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
function ribbonPoint(t,band,time){const mobile=width<820,cx=mobile?width*.52:width*.63,cy=height*.48,phase=band*Math.PI/3+scrollProgress*Math.PI*1.5,radius=Math.min(width,height)*(mobile?.18:.27)*(1+band*.025),morph=scrollProgress*1.3,angle=t*Math.PI*2+phase+time*.00006*(band%2?1:-1);return{x:cx+Math.cos(angle)*(radius*(.72+Math.sin(angle*3+band)*.18))+Math.sin(phase)*80*morph+(pointerX-.5)*(18+band*2),y:cy+Math.sin(angle*2+phase)*radius*.58+(band-2.5)*10*morph+(pointerY-.5)*(14+band*2)}}
function draw(time=0){ctx.clearRect(0,0,width,height);for(let band=0;band<6;band++){const active=band===activeSystem||Math.round(scrollProgress*5)===band;ctx.strokeStyle=active?`rgba(200,255,24,${reduceMotion?.52:.64})`:`rgba(220,224,216,${reduceMotion?.18:.25})`;ctx.lineWidth=active?1.1:.65;for(let strand=0;strand<9;strand++){ctx.beginPath();for(let i=0;i<=90;i++){const t=i/90,p=ribbonPoint(t,band,time),w=(strand-4)*1.8,x=p.x+Math.cos(t*Math.PI*6+band)*w,y=p.y+Math.sin(t*Math.PI*4+band)*w;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}}if(!reduceMotion)requestAnimationFrame(draw)}
function setSystem(index){activeSystem=index;systemItems.forEach((item,i)=>{item.classList.toggle('active',i===index);item.setAttribute('aria-pressed',String(i===index))});document.querySelector('#active-system').textContent=systemItems[index].querySelector('b').textContent}
function setProject(index){activeProject=index;const p=projects[index];projectButtons.forEach((button,i)=>{button.classList.toggle('active',i===index);button.setAttribute('aria-selected',String(i===index))});document.querySelector('#project-index').textContent=`0${index+1} / 03`;document.querySelector('#project-title').textContent=p.title;document.querySelector('#project-description').textContent=p.description;document.querySelector('#project-type').textContent=p.type;setSystem([1,0,2][index])}
systemItems.forEach((item,i)=>{item.addEventListener('mouseenter',()=>setSystem(i));item.addEventListener('focus',()=>setSystem(i));item.addEventListener('click',()=>setSystem(i))});projectButtons.forEach((button,i)=>button.addEventListener('click',()=>setProject(i)));
const menuButton=document.querySelector('.menu-control'),menu=document.querySelector('#menu-panel'),menuClose=document.querySelector('.menu-close');function toggleMenu(open){menu.hidden=!open;menuButton.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':'';if(open)menuClose.focus()}menuButton.addEventListener('click',()=>toggleMenu(menu.hidden));menuClose.addEventListener('click',()=>toggleMenu(false));menu.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>toggleMenu(false)));addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden)toggleMenu(false)});
function updateClock(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('en-US',{hour12:false})}updateClock();setInterval(updateClock,1000);addEventListener('resize',resize);addEventListener('scroll',()=>{scrollProgress=Math.min(1,scrollY/Math.max(innerHeight*4,1));document.querySelector('.rail-line i').style.height=`${20+scrollProgress*80}%`},{passive:true});if(!reduceMotion&&finePointer)addEventListener('pointermove',e=>{pointerX=e.clientX/innerWidth;pointerY=e.clientY/innerHeight;cursor.style.opacity='1'},{passive:true});resize();setSystem(0);setProject(0);draw();
if(window.gsap){gsap.registerPlugin(ScrollTrigger,SplitText,CustomEase,Observer);CustomEase.create('studio','M0,0 C0.16,1 0.3,1 1,1');if(!reduceMotion){const split=new SplitText('.hero h1',{type:'lines,words',linesClass:'line',wordsClass:'word'});gsap.from(split.words,{yPercent:120,autoAlpha:0,stagger:.035,duration:.9,ease:'studio'});gsap.from('.hero-copy,.scene-meta,.discipline-map,.scroll-cue',{y:18,autoAlpha:0,stagger:.08,duration:.7,ease:'studio',delay:.35});document.querySelectorAll('.scene:not(.hero)').forEach(scene=>{const content=scene.querySelectorAll('.scene-heading,.system-list,.system-readout,.project-stage,.method-track,.connect-copy');gsap.from(content,{y:60,autoAlpha:0,stagger:.1,ease:'studio',scrollTrigger:{trigger:scene,start:'top 72%',end:'top 32%',scrub:.65}})});document.querySelectorAll('.scene').forEach((scene,index)=>ScrollTrigger.create({trigger:scene,start:'top center',end:'bottom center',onToggle:self=>{if(self.isActive)document.querySelectorAll('.section-rail li').forEach((li,i)=>li.classList.toggle('active',i===index))}}));if(finePointer){gsap.set(cursor,{xPercent:-50,yPercent:-50});const cx=gsap.quickTo(cursor,'x',{duration:.16,ease:'power3.out'}),cy=gsap.quickTo(cursor,'y',{duration:.16,ease:'power3.out'});addEventListener('pointermove',e=>{cx(e.clientX);cy(e.clientY)},{passive:true});document.querySelectorAll('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>gsap.to(cursor,{scale:1.8,duration:.2}));el.addEventListener('mouseleave',()=>gsap.to(cursor,{scale:1,duration:.2}))})}Observer.create({target:window,type:'wheel,touch',preventDefault:false,tolerance:24})}else gsap.set('.scene-heading,.system-list,.system-readout,.project-stage,.method-track,.connect-copy,.hero-copy,.scene-meta,.discipline-map,.scroll-cue',{clearProps:'all',autoAlpha:1})}
setSystem(0);
projectButtons.forEach(button=>button.type='button');
